declare module '*.png'
declare module '*.svg'
declare module '*.jpg'
declare module '*.jpeg'
declare module 'gatsby-plugin-gdpr-cookies'
declare module 'mdx-utils'
declare module 'prism-react-renderer/prism'
