[context.production]
  command = "yarn build && cp .netlify/_redirects public/_redirects"
  publish = "public/"

[context.deploy-preview]
  command = "yarn build && cp .netlify/_redirects public/_redirects"
  publish = "public/"

[context.develop]
  command = "yarn build && cp .netlify/_redirects public/_redirects"
  publish = "public/"
