[context.production]
  command = "yarn build && cp .netlify/_redirects_production public/_redirects"
  publish = "public/"

[context.deploy-preview]
  command = "yarn build && cp .netlify/_headers_develop public/_headers"
  publish = "public/"

[context.develop]
  command = "yarn build && cp .netlify/_headers_develop public/_headers"
  publish = "public/"
