name: Bug report (website related)
description: Let us know about an issue you experienced on https://docs.substrate.io/
title: '[WEBSITE BUG]: '
labels: ['bug', 'web-dev']
body:
  - type: markdown
    attributes:
      value: |
        Thank you so much for taking the time to report a problem!
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other (please write below)
    validations:
      required: false
  - type: textarea
    id: bug
    attributes:
      label: Bug report for the website
      description: What happened?
      placeholder: Describe the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Provide the steps that led to the discovery of the issue.
      placeholder: Describe what you were doing so we can reproduce the problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: 'Thanks again for completing this report!'
