module.exports = {
  title: 'Substrate_',
  siteUrl: `${process.env.GATSBY_DOCS_URL || 'https://docs.substrate.io'}`,
  image_og: `${process.env.GATSBY_DOCS_URL}/img/substrate_og.png`,
  description:
    'Substrate enables developers to quickly and easily build future-proof blockchains optimized for any use case.',
  keywords: [
    'Blockchain',
    'Polkadot',
    'Substrate',
    'Web3.0',
    'Parity Technologies',
    'Technology',
    'Decentralization',
    'Build',
  ],
  author: 'Parity/Web3F WebDev Team',
  pressEmail: 'press@parity.io',
  email: 'info@parity.io',
  twitter: 'https://twitter.com/substrate_io',
  linkedIn: 'https://www.linkedin.com/company/paritytech',
  element: 'https://matrix.to/#/#substrate-technical:matrix.org',
  github: 'https://github.com/paritytech/substrate',
  telegram: 'https://t.me/parity_technologies',
  gitter: 'https://gitter.im/paritytech/parity',
  stackOverflow: 'https://stackoverflow.com/questions/tagged/substrate',
  privacy: 'https://www.parity.io/privacy/',
  terms: 'https://www.parity.io/terms',
  youtube: 'https://www.youtube.com/c/ParityTech',
  crowdcast: 'https://www.crowdcast.io/e/substrate-seminar-2',
  substrateIO: `${process.env.GATSBY_IO_URL}`,
}
